### ISSUE TITLE
Clock rendering crashes game

### ISSUE THREAD

**Issue by neoNoteCoder** [nekomaster1000/Infernal-Expansion#171]
**Describe the Bug:**
If the game calls for a clock to load, once the item appears it will crash the game.

**How to Reproduce:**
Find an instance where the clock renders, such as finding it in the creative menu, crafting recipe, spawning via command

**Expected Behavior:**
The game crashes once the item appears.

**Version Information:**
 - Mod Version: 2.0.0 Beta 6
 - Other mods that were running when the crash happened: sodium-forge 2.1
[crash-2021-07-16_15.22.00-client.txt](https://github.com/infernalexp/Infernal-Expansion/files/6833288/crash-2021-07-16_15.22.00-client.txt)

**Comment by nekomaster1000** [comment]
This was fixed in our latest update - Sorry about that! https://modrinth.com/mod/infernalexpansion/version/OQUJ8pPr

**Comment by SwanX1** [comment]
Duplicate of #170 

> This was fixed in our latest update - Sorry about that! https://modrinth.com/mod/infernalexpansion/version/OQUJ8pPr

Not fixed, just disabled the feature that caused this
